on:
  push:
    tags:
      - 'release*'
name: CI-Release
permissions:
  contents: write
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: LibrePythonista_PyEditor.flatpak
        manifest-path: io.github.amourspirit.LibrePythonista_PyEditor.yml
        cache-key: flatpak-builder-${{ github.sha }}
    - name: Upload Flatpak
      uses: actions/upload-artifact@v4
      with:
        name: LibrePythonista_PyEditor.flatpak
        path: LibrePythonista_PyEditor.flatpak
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: LibrePythonista_PyEditor.flatpak
        path: .
    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v2
      with:
        files: LibrePythonista_PyEditor.flatpak
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}