on:
  push:
    branches: [main]
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: LibrePythonista_PyEditor.flatpak
        manifest-path: io.github.amourspirit.LibrePythonista_PyEditor.yml
        cache-key: flatpak-builder-${{ github.sha }}
    - name: Upload Flatpak
      uses: actions/upload-artifact@v3
      with:
        name: LibrePythonista_PyEditor.flatpak
        path: LibrePythonista_PyEditor.flatpak